version: '3.8'

services:
  cowrie-honeypot:
    build:
      context: .
      dockerfile: Dockerfile.cowrie
    container_name: cowrie-honeypot
    ports:
      - "2222:2222"  # SSH honeypot
      - "2223:2223"  # Telnet honeypot
      - "5000:5000"  # API server
    volumes:
      - cowrie-logs:/home/cowrie/cowrie/var/log
      - cowrie-downloads:/home/cowrie/cowrie/var/lib/cowrie/downloads
    environment:
      - COWRIE_LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - honeypot-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: cowrie-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - honeypot-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    container_name: cowrie-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - honeypot-network

volumes:
  cowrie-logs:
  cowrie-downloads:
  elasticsearch-data:

networks:
  honeypot-network:
    driver: bridge
